### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by soupman99** [optimizely/optimizely-cordova-plugin#1]
Any ETA for when documentation will be available?  Even something super brief would be helpful.

**Comment by pawurb** [comment]
:+1:

**Comment by mikeproeng37** [comment]
@soupman99 sorry I haven't been responsive. I added a bit more doc on how to get started and also documented the JS interface `window.optimizely` a little better. Hopefully that can help you get started.

**Comment by elliotstokes** [comment]
Would it be possible to document some of the limitations of the cordova interface to optimizely over what you would be able to do with a native app.

**Comment by mikeproeng37** [comment]
@soupman99 @pawurb @elliotstokes I have added more documentation to the README. Please let me know if there is anything else you'd like to see on it.
