### ISSUE TITLE
Cannot get an iOS project to detect my app

### ISSUE THREAD

**Issue by jmfryan** [optimizely/optimizely-cordova-plugin#2]
I'm trying to use this plugin by running the following code after my app starts: 

`window.optimizely.startOptimizely("<TOKEN>", console.log, console.error);`

I get the message `Optimizely started` but the web UI doesnt reflect that my app has connected. And I cant seem to create any variables or experiments.

Any ideas?

**Comment by mikeproeng37** [comment]
@jmfryan I have just updated to the latest version of the iOS SDK. Can you try again and let me know if it works for ya?
